name: Codex Auto-merge (by label, live)

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited
      - unlabeled

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_auto_merge:
    runs-on: ubuntu-latest

    env:
      TARGET_LABEL: "label:codex:automerge"

    steps:
      - name: Resolve PR/REPO
        id: ctx
        run: |
          echo "PR=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          echo "REPO=${{ github.repository }}" >> "$GITHUB_OUTPUT"

      - name: Check label via GitHub API (live)
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR:  ${{ steps.ctx.outputs.PR }}
          REPO: ${{ steps.ctx.outputs.REPO }}
          TARGET_LABEL: ${{ env.TARGET_LABEL }}
        run: |
          set -euo pipefail
          echo "Target label: $TARGET_LABEL"
          gh pr view "$PR" --repo "$REPO" --json labels \
            | tee labels.json \
            | jq -e --arg L "$TARGET_LABEL" '
                [.labels[].name] | index($L) != null
              ' >/dev/null \
            && echo "has_label=true"  >> "$GITHUB_OUTPUT" \
            || echo  "has_label=false" >> "$GITHUB_OUTPUT"
          echo "Labels now:" && jq -r '.labels[].name' labels.json || true

      - name: Exit if label is missing
        if: steps.check.outputs.has_label != 'true'
        run: |
          echo "No '${{ env.TARGET_LABEL }}' label on PR; skipping auto-merge."
          exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge now (if CLEAN) or enable auto-merge (try all methods)
        en
