name: Codex Auto-merge (by label)

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_auto_merge:
    if: >
      github.event.pull_request.draft == false &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'codex:automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable auto-merge on this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
          echo "Auto-merge enabled for PR #${{ github.event.pull_request.number }}"
