name: Codex Auto-merge (by label)

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize, ready_for_review, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_auto_merge:
    # ПРОСТОЕ и надёжное условие: PR не draft И список имен меток содержит "codexautomerge"
    if: >
      github.event.pull_request.draft == false &&
      contains(github.event.pull_request.labels.*.name, 'codexautomerge')
    runs-on: ubuntu-latest
    steps:
      - name: Debug labels & action (temporary)
        run: |
          echo "action=${{ github.event.action }}"
          echo "draft=${{ github.event.pull_request.draft }}"
          echo "labels=${{ toJson(github.event.pull_request.labels) }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable auto-merge on this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge "$PR" --repo "$REPO" --merge --auto
          echo "::notice::Auto-merge enabled for PR #$PR"
