name: Codex Labeler (v3, target)

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - edited
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  contents: read

jobs:
  label_by_codex_activity:
    runs-on: ubuntu-latest
    env:
      TARGET_LABEL: "codexAutomerge"
      # Добавь сюда точные логины своих ботов/интеграций, когда зафиксируешь их
      ALLOWED_AUTHORS_JSON: '["chatgpt-codex-connector[bot]","openai-codex[bot]","openai]()
