name: Codex Auto-merge (by label)

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize, ready_for_review, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug labels
        run: |
          echo "Labels JSON:"
          echo '${{ toJson(github.event.pull_request.labels) }}'

      - name: Check for codexautomerge label
        id: check
        run: |
          echo '${{ toJson(github.event.pull_request.labels) }}' | grep -q '"name":"codexautomerge"' && \
            echo "has_label=true" >> $GITHUB_OUTPUT || \
            echo "has_label=false" >> $GITHUB_OUTPUT

      - name: Checkout repository
        if: steps.check.outputs.has_label == 'true'
        uses: actions/checkout@v4

      - name: Enable auto-merge on this PR
        if: steps.check.outputs.has_label == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge "$PR" --repo "$REPO" --merge --auto
          echo "::notice::Auto-merge enabled for PR #$PR"
