# (YAML · GitHub Actions) — авто-метка по активности Codex
name: Codex Labeler

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  label_by_codex_activity:
    # Ограничим событиями только для PR (issue_comment может быть и в issue)
    if: >
      (github.event_name == 'issue_comment' && github.event.issue.pull_request) ||
      (github.event_name == 'pull_request_review')
    runs-on: ubuntu-latest
    steps:
      - name: Detect PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> "$GITHUB_OUTPUT"
            echo "ACTOR=${{ github.event.comment.user.login }}" >> "$GITHUB_OUTPUT"
            echo "BODY<<EOF" >> "$GITHUB_OUTPUT"
            echo "${{ github.event.comment.body }}" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
            echo "ACTOR=${{ github.event.review.user.login }}" >> "$GITHUB_OUTPUT"
            echo "BODY<<EOF" >> "$GITHUB_OUTPUT"
            echo "${{ github.event.review.body }}" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          fi

      - name: Decide if it looks like Codex
        id: guard
        env:
          ACTOR: ${{ steps.pr.outputs.ACTOR }}
          BODY: ${{ steps.pr.outputs.BODY }}
          # Список допустимых авторов — потом подставите точный логин бота Codex (например, openai-codex[bot])
          ALLOWED_AUTHORS: '["openai-codex[bot]","openai[bot]","codex-bot","codex-cloud-bot"]'
        run: |
          set -euo pipefail
          echo "Actor: $ACTOR"
          # 1) Автор — в белом списке?
          if echo "$ALLOWED_AUTHORS" | jq -e --arg a "$ACTOR" 'index($a) != null' >/dev/null; then
            echo "looks_like_codex=1" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # 2) Фразы-маркеры в тексте (резерв, если логин пока неизвестен)
          MARKERS="Codex Review|@codex|Suggested by Codex|Generated by Codex|OpenAI Codex"
          if printf '%s' "$BODY" | grep -Eiq "$MARKERS"; then
            echo "looks_like_codex=1" >> "$GITHUB_OUTPUT"
          else
            echo "looks_like_codex=" >> "$GITHUB_OUTPUT"
          fi

      - name: Add label codex:automerge
        if: steps.guard.outputs.looks_like_codex == '1'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.pr.outputs.PR_NUMBER }}
        run: |
          gh pr edit "$PR_NUMBER" --add-label "codex:automerge"
